env:development:
  - changed-files:
    - any-glob-to-any-file: 'environment/development/**'

env:testing:
  - changed-files:
    - any-glob-to-any-file: 'environment/testing/**'

env:acceptance:
  - changed-files:
    - any-glob-to-any-file: 'environment/acceptance/**'

env:production:
  - changed-files:
    - any-glob-to-any-file: 'environment/production/**'
