name: "Generate Labeler Config"
on:
  schedule:
    # Every Sunday at 06:00 UTC
    - cron: "0 6 * * 0"
  workflow_dispatch:

jobs:
  gen-labeler:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: astral-sh/setup-uv@v8.1.0
    - name: Regenerate .github/labeler.yml
      run: uv run utils/gen_labeler.py
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v8
      with:
        commit-message: '[SCOUT] Regenerate labeler config with current teams'
        branch: gen-labeler
        title: '[SCOUT] Regenerate labeler config with current teams'
